name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/vpc

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform/vpc

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/vpc

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform/vpc
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}